import type { ArcanistInput, ExternalBonuses } from '../calc/types';

/** No external bonuses from other systems. */
export const FRESH_EXTERNAL: ExternalBonuses = {
  cardSoftMaxLoot: 'none',
  cardDenseMaxLoot: 'none',
  cardJaggedMaxLoot: 'none',
  cardAshCraft: 'none',
  cardBrineCraft: 'none',
  cardChasmCraft: 'none',
  cardSpell: {
    runicSurge: 'none',
    rainbowRift: 'none',
    manaflow: 'none',
    radiancy: 'none',
    prismism: 'none',
    veinboyant: 'none',
  },
  cardSuperShiny: 'none',
  arcaneCardCount: 0,
  petMaxEssence: false,
  petBrittle: 0,
  petShiny: 0,
  petSpellPotency: 0,
  obeliskShiny: false,
  obeliskSuperShiny: false,
  skillShiny: false,
  skillBrittle: false,
  storeShiny: false,
  constructSuperShiny: 0,
  contractRuneCraft: 0,
  storeRuneCraft: 0,
  spellDurationMulti: 1,
};

/** A freshly unlocked Arcanist: nothing bought, nothing unlocked. */
export const FRESH_INPUT: ArcanistInput = {
  essence: {
    essenceMine: 0,
    flatDamage1: 0,
    softMaxLoot: 0,
    shinyChance1: 0,
    critChance1: 0,
    flatDamage2: 0,
    denseMaxLoot: 0,
    armorPen: 0,
    superCrit1: 0,
    flatDamage3: 0,
    damagePct: 0,
    shinyLoot: 0,
    shinyChance2: 0,
    critChance2: 0,
    jaggedLoot: 0,
  },
  altars: {
    // The Ash Altar has no unlock cost on the sheet; it is available from the start.
    ash: { unlocked: true, active: false, capacity: 0, travel: 0, craft: 0 },
    brine: { unlocked: false, active: false, capacity: 0, travel: 0, craft: 0 },
    chasm: { unlocked: false, active: false, capacity: 0, travel: 0, craft: 0 },
  },
  spells: {
    runicSurge: { unlocked: false, level: 0, rank: 0 },
    rainbowRift: { unlocked: false, level: 0, rank: 0 },
    manaflow: { unlocked: false, level: 0, rank: 0 },
    radiancy: { unlocked: false, level: 0, rank: 0 },
    prismism: { unlocked: false, level: 0, rank: 0 },
    veinboyant: { unlocked: false, level: 0, rank: 0 },
  },
  exchange: {
    exchangeWizards: 0,
    exchangeTimer: 0,
    arcaneCardDamage: 0,
    rainbowFloorMulti: 0,
    lootbugBankedCap: 0,
    goldenPortalChance: 0,
    starSupergiantMulti: 0,
    wizardLootMulti: 0,
    geminiStarCap: 0,
    unlockVeinboyant: 0,
    prismaticFloorChance: 0,
    shinyFishMulti: 0,
    runeCraftMulti: 0,
  },
  external: FRESH_EXTERNAL,
};
