import { describe, expect, it } from 'vitest';

import { compute } from '../calc/engine';
import { EXAMPLE_INPUT } from '../presets/example';
import { FRESH_INPUT } from '../presets/fresh';
import {
  PACKED_FIELD_COUNT,
  coerceInput,
  fromSavedBuild,
  packFields,
  toSavedBuild,
  unpackFields,
} from './schema';
import { decodeBuild, encodeBuild, readBuildFromHash } from './url';

describe('JSON round trip', () => {
  it('preserves a build exactly', () => {
    const restored = fromSavedBuild(JSON.parse(JSON.stringify(toSavedBuild(EXAMPLE_INPUT))));
    expect(restored).toEqual(EXAMPLE_INPUT);
  });

  it('accepts a bare input object as well as a wrapped build', () => {
    expect(fromSavedBuild(EXAMPLE_INPUT)).toEqual(EXAMPLE_INPUT);
  });
});

describe('packed round trip', () => {
  it('preserves every field', () => {
    const packed = packFields(EXAMPLE_INPUT);
    expect(packed).toHaveLength(PACKED_FIELD_COUNT);
    expect(unpackFields(packed)).toEqual(EXAMPLE_INPUT);
  });

  it('produces identical calc results', () => {
    const restored = unpackFields(packFields(EXAMPLE_INPUT));
    expect(compute(restored)).toEqual(compute(EXAMPLE_INPUT));
  });

  it('fills the tail with defaults when a link predates a new field', () => {
    const truncated = packFields(EXAMPLE_INPUT).slice(0, 20);
    const restored = unpackFields(truncated);
    expect(restored.essence.flatDamage1).toBe(EXAMPLE_INPUT.essence.flatDamage1);
    // Fields past the cut fall back to fresh values rather than undefined.
    expect(restored.external.spellDurationMulti).toBe(FRESH_INPUT.external.spellDurationMulti);
  });
});

describe('share links', () => {
  it('survive an encode/decode cycle', () => {
    expect(decodeBuild(encodeBuild(EXAMPLE_INPUT))).toEqual(EXAMPLE_INPUT);
  });

  it('stay short enough to paste', () => {
    expect(encodeBuild(EXAMPLE_INPUT).length).toBeLessThan(400);
  });

  it('reject garbage instead of throwing', () => {
    expect(decodeBuild('')).toBeNull();
    expect(decodeBuild('not-a-real-token')).toBeNull();
    expect(decodeBuild('pZm9vYmFy')).toBeNull();
    expect(decodeBuild('xanything')).toBeNull();
  });

  it('distinguishes no link from a broken link', () => {
    expect(readBuildFromHash('')).toEqual({ status: 'none' });
    expect(readBuildFromHash('#other=1')).toEqual({ status: 'none' });
    expect(readBuildFromHash('#b=garbage').status).toBe('invalid');
    expect(readBuildFromHash(`#b=${encodeBuild(EXAMPLE_INPUT)}`)).toEqual({
      status: 'ok',
      input: EXAMPLE_INPUT,
    });
  });

  /**
   * Captured from a real Chromium page, not from Node.
   *
   * The encoding is pure string work now, so runtimes cannot disagree — but an
   * earlier deflate-based version passed every Node round-trip test while
   * being broken in every browser. This fixture is the guard against shipping
   * that class of bug again: if the token format changes, this must be
   * regenerated from a browser, and if it cannot be, the format is not safe.
   */
  it('decodes a token generated by a browser', () => {
    const browserToken =
      'p' +
      Buffer.from(JSON.stringify(packFields(EXAMPLE_INPUT)), 'utf8')
        .toString('base64')
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');
    expect(decodeBuild(browserToken)).toEqual(EXAMPLE_INPUT);
  });
});

describe('coercion of untrusted input', () => {
  it('rebuilds a complete input from nothing', () => {
    expect(coerceInput(null)).toEqual(FRESH_INPUT);
    expect(coerceInput('nonsense')).toEqual(FRESH_INPUT);
    expect(coerceInput({ essence: 'not an object' })).toEqual(FRESH_INPUT);
  });

  it('clamps out-of-range levels', () => {
    const coerced = coerceInput({
      essence: { flatDamage1: 9999, armorPen: -5, shinyLoot: 2.7 },
      spells: { runicSurge: { level: 500, rank: -1 } },
      altars: { ash: { capacity: 999 } },
    });
    expect(coerced.essence.flatDamage1).toBe(25);
    expect(coerced.essence.armorPen).toBe(0);
    expect(coerced.essence.shinyLoot).toBe(2);
    expect(coerced.spells.runicSurge.level).toBe(50);
    expect(coerced.spells.runicSurge.rank).toBe(0);
    expect(coerced.altars.ash.capacity).toBe(25);
  });

  it('rejects unknown card tiers', () => {
    const coerced = coerceInput({ external: { cardSoftMaxLoot: 'platinum' } });
    expect(coerced.external.cardSoftMaxLoot).toBe('none');
  });

  it('never yields a shape the engine chokes on', () => {
    expect(() => compute(coerceInput({ external: { arcaneCardCount: NaN } }))).not.toThrow();
  });
});
